### ISSUE TITLE
Current conference management tools are not ideal for this model

### ISSUE THREAD

**Issue by sjmurdoch** [ieee-security/ongoing-submission-plan#4]
Another issue we hit with PETS is that the current state of conference management tools is not ideal for this model. We muddled through with HotCRP and some custom scripts, but it was a lot of work to manage 4 deadlines per year with a mainly non-overlapping review process, let alone 12. A better tool would make a huge difference.

**Comment by UlfarErl** [comment]
Yes, this is definitely an issue.  To keep things managable, we were thinking of running a different HotCRP server for each year, and copy ongoing submissions between years.  It may even be worth running a different instance for each submission cycle, if we can get the database copying to work out.

This said, the VLDB model has become common enough that Eddie has started dropping hints that we may get some built-in support into HotCRP withing the timeframe of this change for Oakland.

**Comment by sjmurdoch** [comment]
> To keep things managable, we were thinking of running a different HotCRP server for each year, and copy ongoing submissions between years.

That could work. What we did was use the HotCRP multi-conference facility to have a different instance for each edition and copy the PC from one to the next. We did not copy submissions but instead added a link to each re-submission which went to the corresponding paper in the previous edition.

> Eddie has started dropping hints that we may get some built-in support into HotCRP

That would be great!

**Comment by UlfarErl** [comment]
By "adding a link" you mean a URL to the old conference instance page for the paper.was added in some text field for the paper.. And, then, that URL was usable by the PC members that had also been on the PC for that old instance. ?

**Comment by sjmurdoch** [comment]
> By "adding a link" you mean a URL to the old conference instance page for the paper.was added in some text field for the paper

Correct. The abstract, to be precise.

> And, then, that URL was usable by the PC members that had also been on the PC for that old instance. ?

Yes. This was OK because we did our best to make sure that the re-submissions were reviewed by the same PC members as reviewed the original one. If a person had left the PC by the time the re-submission was made we still added them to HotCRP but did not allocate them any papers except the re-submission.

**Comment by UlfarErl** [comment]
OK, I'm closing this issue but we'll keep the options you mentioned in mind.
